import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Layout_Parts/header";"./Layout_Parts/header";
import MainNavigation from "./Layout_Parts/main_navigation";
import Footer from "./Layout_Parts/footer"; "./Layout_Parts/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
          <link rel="stylesheet" href="/assets/css/style.css" />
          <script src="/assets/js/bootstrap.min.js"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container-fluid header">
            {/* <div className="toggleMainMenu">
              <div className="buttonToggleMainMenu"></div>
            </div> */}
            <div className="row main-primary-menu">
                    <MainNavigation />
            </div>
            <Header />
        </div>
        <div className="container-fluid">
          <div role="breadcrumb" className="row">
            
          </div>
          <div role="main" className="maincontent">
              {children}
          </div>    
        </div>
        <div className="container-fluid">
              <Footer />
        </div>
      </body>
    </html>
  );
}
